FROM ubuntu:14.04

RUN apt-get update && apt-get upgrade -y

RUN echo "Asia/Tokyo" > /etc/timezone && dpkg-reconfigure --frontend noninteractive tzdata
RUN apt-get install language-pack-ja locales
RUN locale-gen ja_JP.UTF-8
ENV LANG=ja_JP.UTF-8
ENV LANGUAGE=ja_JP:ja
ENV LC_ALL=ja_JP.UTF-8


RUN apt-get install -y git vim tmux
RUN apt-get install -y build-essential gfortran


### python ###
RUN apt-get install -y python-setuptools
RUN apt-get install -y python-pip
RUN apt-get install -y python-dev
RUN apt-get install -y python-numpy
RUN apt-get install -y python-scipy
RUN apt-get install -y python-matplotlib
RUN apt-get install -y python-pandas
RUN apt-get install -y python-sympy
RUN apt-get install -y ipython
RUN apt-get install -y ipython-notebook
RUN pip install chainer
RUN pip install scikit-learn
RUN pip install notebook
RUN pip freeze --local | grep -v '^\-e' | cut -d = -f 1 | xargs pip install -U

RUN apt-get clean
