FROM centos:7


RUN yum update -y && yum clean all
RUN yum install -y epel-release
RUN yum install -y wget gcc gcc-c++ python-pip boost-devel make git
RUN yum yum install zlib-devel bzip2 bzip2-devel readline readline-devel sqlite sqlite-devel openssl openssl-devel

RUN localedef -f UTF-8 -i ja_JP ja_JP.UTF-8
ENV LANG=ja_JP.UTF-8
ENV LANGUAGE=ja_JP:ja
ENV LC_CTYPE=ja_JP.UTF-8


### C++ Boost ###
RUN wget https://sourceforge.net/projects/boost/files/boost/1.62.0/boost_1_62_0.tar.gz
RUN tar xvzf boost_1_62_0.tar.gz
RUN cd boost_1_62_0 && sh bootstrap.sh && ./b2 install -j2

RUN rm boost_1_62_0 boost_1_62_0.tar.gz


### JUMAN++ ###
RUN wget http://lotus.kuee.kyoto-u.ac.jp/nl-resource/jumanpp/jumanpp-1.01.tar.xz
RUN tar xJvf jumanpp-1.01.tar.xz
RUN cd jumanpp-1.01 && ./configure && make && make install

RUN rm -rf jumanpp-1.01 jumanpp-1.01.tar.xz


### mecab ###
RUN wget -O mecab-0.996.tar.gz "https://drive.google.com/uc?export=download&id=0B4y35FiV1wh7cENtOXlicTFaRUE"
RUN tar zxvf mecab-0.996.tar.gz
RUN cd mecab-0.996 && ./configure && make && make install

RUN wget -O mecab-ipadic-2.7.0-20070801.tar.gz "https://drive.google.com/uc?export=download&id=0B4y35FiV1wh7MWVlSDBCSXZMTXM"
RUN tar zxvf mecab-ipadic-2.7.0-20070801.tar.gz
RUN cd mecab-ipadic-2.7.0-20070801 && ./configure --with-charset=utf8 && make && make install

RUN rm -rf mecab-0.996.tar.gz mecab-0.996 mecab-ipadic-2.7.0-20070801.tar.gz mecab-ipadic-2.7.0-20070801

### python ###
RUN yum install python34 python34-devel
RUN wget https://bootstrap.pypa.io/get-pip.py
RUN python3.4 get-pip.py
RUN easy_install virtualenv
RUN virtualenv -p `which python3.4` venv/py34_nlp
RUN source venv/py34_nlp/bin/activate && pip install six numpy scipy matplotlib pandas
RUN source venv/py34_nlp/bin/activate && pip install gensim chainer scikit-learn mecab-python3
RUN echo "/usr/local/lib" >> /etc/ld.so.conf
RUN ldconfig

### PyKNP ###
RUN wget http://nlp.ist.i.kyoto-u.ac.jp/nl-resource/knp/pyknp-0.3.tar.gz
RUN tar xvf pyknp-0.3.tar.gz
RUN source venv/py34_nlp/bin/activate && cd pyknp-0.3 && python setup.py install

RUN rm -rf pyknp-0.3.tar.gz pyknp-0.3

### fastText ###
RUN git clone https://github.com/facebookresearch/fastText.git
RUN cd fastText && make
RUN ln -s /fastText/fasttext /usr/local/bin/fasttext
